# Generated by Django 5.0.3 on 2024-03-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=10)),
                ('constituency', models.CharField(max_length=20)),
                ('total_voters', models.IntegerField()),
                ('secured_votes', models.IntegerField()),
                ('status', models.CharField(choices=[('elected', 'ELECTED'), ('defeated', 'DEFEATED')], max_length=10)),
            ],
        ),
    ]
